---
title: "Assignment 4: Study design"
author: "Sivert Helland Veseth"
format: 
  html:
    number-sections: true
    toc: true
    code-fold: true
execute: 
  warning: false
editor: visual
editor_options: 
  chunk_output_type: console
bibliography: resources/referanser.bib
csl: resources/apa.csl
---

# Innledning

Tradisjonelt sett er plyometrisk trening den vanligste treningsmetoden for å forbedre en persons evne til rask kraftutvikling, og er derfor ofte brukt innen sprint- og hoppidretter (**ref, en metaanalyse maybe**). Selv om evnen til rask kraftutvikling er viktig for prestasjon, er utvikling av maksimal kraft også viktig. Et individs evne til å produsere impuls, som er et produkt av rate of force development (RFD) og maksimal kraft, er en avgjørende egenskapen for prestasjon i eksplosive og kraftfulle idretter (**ref, boken om impuls**). For å bedre forstå hvordan plyometrisk trening påvirker prestasjon i slike idretter, har jeg valgt ut fem studier som ser nærmere på effekten av plyometrisk trening på kraftutvikling. 

De fem inkluderte studiene vil bli analysert ved hjelp av QALMRI-metoden ("Question", "Alternatives", "Methods", "Results" og "Inferences"), en evidensbasert tilnærming som sikrer en grudig forståelse av nøkkelpunktene og kritisk vurdering av empiriske artikler (@Brosowsky2020). I stedet for å gi en detaljert gjennomgang av hver enkelt studie, vil jeg se på studienes design og valg av statistiske analyser som er brukt for å besvare forskningsspørsmålene. Til slutt vil jeg komme med min anbefaling for hvordan fremtidige studier kan designes for best mulig å undersøke effekten av plyometrisk trening på muskelstyrke. 

# Analyse

**Studie 1:** A COMPARISON OF THE EFFECTS OF SHORT-TERM PLYOMETRIC AND RESISTANCE TRAINING ON LOWER-BODY MUSCULAR PERFORMANCE

- Anecdotal evidence indicates that plyometric training may be as useful in developing some parameters of lower-body performance as resistance training. Therefore, the purpose of this study was to compare the effects of short-term plyometric and resistance training on lower-body muscular performance including high-speed muscular strength (standing long jump, vertical jump), low-speed muscular strength (onerepetition maximal back squat), running speed (20-m
sprint), and running agility (505 agility test). These 2 types of training are being compared to offer an alternative to short-term resistance training for coaches and athletes with time and space constraints. 
- **We hypothesize that similar lower-body muscular performance results will be obtained from short-term either plyometric or resistance training.**

**Studie 2:** Effects of Plyometric Training on Sonographic Characteristics of Quadriceps Muscle and Patellar Tendon, Quadriceps Strength, and Jump Height in Adolescent Female Volleyball Players

- Thus, this study aimed to investigate the effects of 6-week plyometric training on the sonographic characteristics of the VL including muscle thickness and EI, and PT–CSA, quadriceps strength, and the vertical jump performance of adolescent female volleyball athletes. 
- **It was hypothesized that plyometric exercise would increase VL thickness, PT–CSA, quadriceps strength, and vertical jump height but decrease VL–EI in adolescent female**
volleyball players.

**Studie 3:** EFFECTS OF PLYOMETRIC AND RESISTANCE TRAINING ON MUSCLE STRENGTH, EXPLOSIVENESS, AND NEUROMUSCULAR FUNCTION IN YOUNG ADOLESCENT SOCCER PLAYERS

- It is therefore the purpose of this study to compare the effects of FW resistance vs. plyometric training, in young
adolescent athletes, on jump performance, dynamometer measured muscular strength and explosiveness, neuromuscular parameters, and muscle hypertrophy. 
- **It was hypothesized that both FW resistance and plyometric training will result in improved muscular and jump performance. It was further hypothesized that changes induced by FW RT will be mediated more by morphological adaptations, whereas plyometric-induced changes would be mediated mostly by enhanced neuromuscular activation.**

**Studie 4**: Evaluation of Plyometric Exercise Training, Weight Training, and Their Combination on Vertical Jumping Performance and Leg Strength

- Researchers and practitioners assumed that these characteristics of plyometric exercises would facilitate significant gains in muscle strength and power and therefore optimize jumping performance.
- It seems that researchers have not come to an agreement about the relative effectiveness of plyometric training compared with weight training or the combination of both in the development of vertical jumping ability
- Therefore, the purpose of the present investigation was to determine <u><strong>how selected variables of vertical jumping performance, namely, leg power, jumping height, flight time, ground time, and leg strength, are affected by a typical 12-week plyometric training program, a typical 12-week weight-training program, and 12-week training program that combines plyometric exercises and weight training.</strong></u> 

**Studie 5**: MUSCLE ADAPTATIONS TO PLYOMETRIC VS.RESISTANCE TRAINING IN UNTRAINED YOUNG MEN

- Thus, in contrast to the most common beliefs, the possibility exists that PT may induce changes in muscle morphology that resemble those of CRT. However, information on this aspect is very limited. Furthermore, direct comparisons on functional strength performance effects of CRT vs. PT also are scarce.
- The purpose of this study, therefore, was to compare possible changes in muscle strength, power, and morphology
induced by PT vs. CRT of equal time and effort in individuals with no prior history of strength training or involvement in sports activities involving SSC movement patterns. 
- More specifically, we wanted to 1) compare the adaptive changes both in single-fiber and whole-muscle morphology in PT vs. CRT, and 2) to compare the adaptive changes in maximal muscle strength and power induced by PT and CRT. <u><strong>It was hypothesized that PT would predominate over CRT in training-induced muscle power and that CRT would predominate over PT in training-induced muscle hypertrophy and muscle strength.</strong></u>

Besvare spørsmål 1 og 2
1. What was the broader problem the authors are trying to resolve in the study?
2. What are the specific questions the authors are trying to answer?

De utvalgte studiene har som overordnet mål å undersøke hvordan plyometrisk trening påvirker sentrale aspekter av fysisk prestasjon, inkludert maksimal styrke, eksplosivitet og muskeltykkelse, som er avgjørende i eksplosive og kraftfulle idretter. Hver studie adresserer hver sin spesifikke problemstilling knyttet til dette målet. Fatourus et al. (2000) ønsker å sammenligne effekten ploymetrisk trening, tradisjonell styrketrening og kombinasjonstrening har på vertikal hopp prestasjon (@Fatouros2000). Vissing et al. (2008) undersøker hvilke adaptive endringene i maksimal styrke og power som skjer som følge av enten tradisjonell styrketrening eller plyometrisk styrketrening (@Vissing2008). McKinlay et al. (2018) adresserer hvordan plyometrisk trening påvirker nevromuskulære funksjoner og muskulære tilpasninger hos unge fotballutøvere (@McKinlay2018). Whitehead et al. (2018) fokuserer på kortsiktige effekter av plyometrisk og styrketrening på muskelstyrke og eksplosiv prestasjon (@Whitehead2018). Mens Harput et al. (2023) utforsker effekten av plyometrisk trening på hoppytelse, muskeltykkelse og muskelstyrke i quadriceps hos unge kvinnlige volleyballspillere (@Harput2023).  

Svar på spørsmål 3
3. Is the specific question framed as an hypothesis or a question?

Ingen av studiene definerer et klart forskningsspørsmål knytt til problemstillingen sin. De fleste av de aktuelle studiene presenterer en klar hypotese om at plyometrisk trening vil gi lik eller bedre resultater i eksplosivitet, muskelstyrke eller nevromuskulære tilpasninger sammenlignet med andre treningsmetoder, som Harput et al. (2023), Vissing et al. (2008), McKinlay et al. (2018) og Whitehead et al. (2018) (@McKinlay2018;@Harput2023;@Vissing2008;@Whitehead2018). Fatouros et al. (2000) derimot, beskriver heller formålet med studien uten å formulere et forskningsspørsmål eller en hypotese (@Fatouros2000). Tabell 1 viser en oversikt av de enkelte studiene sine hypoteser eller beskrivelse. 

Figur 1

Hypotese:

Whitehead - Det vil ikke være noen signifikant forskjell i muskelprestasjon i underekstremitetene etter kortsiktig plyometrisk trening sammenlignet med styrketrening. 


McKinley - Både styrketrening med frie vekter og plyometrisk trening vil føre til signifikante forbedringer i muskelprestasjon og prestasjon i hopp. Det forventes at endringene fra styrketreningen vil i hovedsak være grunnet morfologiske tilpasninger, mens endringene fra plyometrisk trening vil være grunnet forbedret nevromuskulær aktivering. 

Harput - Den plyometrisk trening vil føre til økt tykkelsen av vastus lateralis, tverrsnittsarealet til patellarsenen, quadriceps-styrke og vertikalhopp-høyde, samtidig som det vil redusere ekkointensitet i vastus lateralis hos unge kvinnelige volleyballspillere. 


Vissing - Plyometrisk trening vil ha større effekt enn tradisjonell styrketrening på eksplosiv muskelkraft, mens tradisjonell styrketrening vil ha større effekt enn plyometrisk trening på muskelhypertrofi og muskelstyrke. 

Beskrivelse

Fatouros - Formålet med studien var å undersøke hvordan utvalgte variabler på vertikalhopp-prestasjon er påvirket av plyometrisk trening, styrketrening eller en kombinasjon av dei to nevnte treningsmetodene.


~~Spesifikt spørsmål i hver studie - Kanskje legge det inn i en tabell??:~~

~~- Fatouros et al. (2000): Hvordan sammenligner plyometrisk trening, styrketrening og en kombinasjon av disse med hensyn til effekt på prestasjon i vertikal hopp og benstyrke?~~
~~- Vissing et al. (2008): Hvilke forskjeller i adaptive endringer i maksimal styrke og power, vil det være mellom maksimal styrketrening og plyometrisk trening hos unge, utrente menn?~~
~~- McKinlay et al. (2018): Hva er forskjellene mellom plyometrisk og styrketrening på nevromuskulær funksjon og muskulære tilpasninger hos unge fotballspillere?~~
~~- Whitehead et al. (2018): Hva er de kortisiktige effektene av plyometrisk trening versus styrketrening på muskelstyrke og eksplosiv prestasjon?~~
~~- Harput et al. (2023): Hvordan påvirker plyometrisk trening hopp-prestasjon, patellarsenen, muskeltykkelse og muskelstyrke i quadriceps hos unge volleyballspillere?~~


Svar deretter på spørsmål 4 om det er relevant
If the authors have formulated a hypothesis, what alternative explanations can you think of that could potentially explain the data that the authors hypothesize?

En likhet med hypotesene som presenteres i studiene, er at plyometrisk trening antas å resultere i større forbedringer på muskelens evne til å generere kraft hurtig, altså eksplosivitet (**ref, kanskje sjekke Styrketrening boka**). Det finnes imidlertid flere alternative forklaringer på resultatene som kan påvirke dataene. En mulig forklaring kan være at intensiteten i den plyometriske treningen var høyere, noe som førte til forbedringer uavhengig av treningsmetode (**ref, styrkeboka??**). Deltagernes treningsbakgrunn vil også kunne påvirke hvordan de responderer på treningen (**ref**), i tillegg til dagsformen på testdagen, som kan gi ytterligere variasjon i prestasjonene (**ref**). Det vil også være mulig at forbedringene i eksplosivitet er et resultat av nevromuskulære tilpasninger, enn spesifikk effekter av plyometrisk trening (**ref**). I tillegg kan placeboeffekten spille en rolle, da forbedringene ikke er på grunn av treningsformen, men fordi de forventer forbedringer når de deltar i et treningsopplegg (**ref**). 


Svare på spørsmål 5
5. What is the logic of the hypothesis or the question. Try to create a “line of logic” between the introduction and the question/hypothesis.

Plyometrisk trening beskrives som en sentral metode for å forbedre prestasjon der det stilles krav til hurtig kraftutvikling, og antas å kunne gi lignende eller bedre muskulære og nevromuskulære tilpasninger sammenlignet med tradisjonell styrketrening (@Whitehead2018, s.2743-2744;@markovic2010). Samtidig påpekes det at det finnes begrenset forskning på hvorfor plyometrisk trening forbedrer prestasjon, og hvilke spesifikke tilpasninger som ligger bak disse forbedringene (@McKinlay2018, s.3039-3040;@Harput2023, s.89;@Vissing2008, s.1800;@Fatouros2000, s.471). Basert på disse kunnskapshullene har forfatterne av de utvalgte studiene formulert hypoteser om at plyometrisk trening vil kunne gi lik eller større forbedring i prestasjon i bevegelser som krever rask kraftutvikling, sammenlignet med tradisjonell styrketrening, og samtidig undersøke hvilke underliggende mekanisker som fører til disse tilpasningene.  

Kan man kanskje her lage ein figur? Det overordna målet øverst og trekke det ut til kva ulike måtene studiene har valgt å svare på spørsmålet. Også derfra kanskje dele dei inn i dei ulike spørsmålene.

## Metode

Svare på spørsmål 6
6. Describe the study design. Use Hulley, (2013), Chapters 7-13 in your analysis.

Valg av studiedesign er avgjørende for å kunne svare på forskningsspørsmålet eller teste hypoteser.Studiedesignet strukturerer studien på en måte som gjør det mulig å trekke holdbare slutninger (@browner2022, s.3). Valget av design avhenger blant annet om man planlegger å igangsette en intervensjon for å undersøke dens effekter. Slike studier, kjent som analytiske studier, prøver å evaluere sammenhenger og trekke slutninger om årsak-virkning-forholdet (@browner2022, s.5). En typisk analytisk studiedesign er en randomisert kontrollert studie (RCT). Før man gjennomfører en slik studie, er det vanlig at deskriptive studier har blitt utført for å undersøke karakteristikker ved en populasjonen, som for eksempel muskelmasse hos eliteutøvere (@browner2022, s.4). En tydelig beskrivelse av studiedesignet og begrunnelse av valget er avgjørende for å gi leserne instinkt i forskerens vurderinger. 

Som nevnt tidligere, er det overordnet målet med de utvalgte studiene å undersøke hvordan plyometrisk trening påvirker fysisk prestasjon, inkludert maksimal styrke, eksplosivitet og muskelmasse. Fire av studiene har valgt å tilfeldig fordele deltakerne til enten å gjennomføre trening (intervensjon) eller ikke (kontroll) (@Fatouros2000;@McKinlay2018;@Vissing2008;@Whitehead2018), slik det gjøres i en RCT-studie. Den femte studien valgte imidlertid et prospektivt kohortdesign, der deltakerne ble fulgt opp over tid uten randomisering (@Harput2023).Ved å randomisere deltagerne mellom gruppene i RCT-studiene minimeres påvirkningen av konfunderende variabler som kan forstyrre resultatene, mens kohortstudier gir mulioghet til å observere naturlige endringer i en populasjon over tid uten intervensjon i gruppefordelingen (@browner2022, s.4, 6, 116, 196). 

I RCT-studiene som Fatouros et al. (2000), McKinlay et al. (2018), Vissing et al. (2008) og Whitehead et al.(2018) gjennomførte, vil valget om randomisering bidra til å redusere risikoen for at andre faktorer enn treningen selv påvirket resultatene, som treningsbakgrunn, noe som vil styrke validiteten av konklusjonene om årsakssammenheng mellom intervensjon og fysisk prestasjon. Ingen av studiene benyttet derimot blinding i sitt design, noe som kan ha introdusert rapporteringsbias, særlig siden både deltakerne og forskerne visste hvilken gruppe deltakerne tilhørte (@browner2022, s.196, 397). Dette er ikke noe nytt for treningsintervensjoner, der det er praktisk vanskelig å skjule gruppetilhørlighet. 

I kohortstudien av Harput et al. (2023), var det derimot ikke mulig å bruke randomisering. Forskerne fulgte deltakerne over tid for å observere endringer etter en allerede igangsatt treningsintervensjon, noe som tillot forskerne å se naturlige variasjoner i prestasjonene uten inngrep i gruppefordelingen (@browner2022 s.4, 116). Samtidig gjør dette at kohortstudier er mer utsatt for konfunderende variabler, siden deltakerne ikke blir tilfeldig fordelt i grupper. Dette kan påvirke validiteten i forhold til årsakassammenhenger, men samtidig er slike design mer gjennomførbar for å undersøke langtidseffekter i en realistisk setting. 



Basis
Kap 2 s.17-26 - Utvikle studieplan
Kap 3 s.26-39 - Utvalg
Kap 4 s.39-52 - Målinger
kap 5 s.52 - Estimere utvalgsstørrelse

Studiedesign
Kap 8 s.116-138 - Tverrsnitsstudie og kohortstudier
Kap 9 s.138-157 - Case-control studie
Kap 10 s.157-196 - Kausal effekt ved å bruke observasjonsstudier
Kap 11 s.196-221 - Designe RCT
Kap 12 s.221-240 - Alternative studiedesign
Bruke her pensumboken, og forklare dei ulike metodene. 

Spørsmål 7. og 8. kan besvares i samme avsnitt
7. Describe the sample and if the study defines the population.
8. Describe the method of recruiting participants to the study. Did the authors justify their sample size (i.e. did they do a power calculation)?

Ingen av studiene definerer eller beskriver en bestemt populasjon i detalj, og det er varierende grad av informasjon om deltakerne. Generelt tar studiene for seg unge, aktive idrettsutøvere eller utrente menn/ungdommer, men ikke alle går i dybden på demografiske faktorer som kan påvirke generaliserbarheten av resultatene (@browner2022, s.26-27). For eksempel bestod utvalget i Vissing et al. (2008) av en relativt homogen gruppe med utrente menn, mens Harput et al. (2023) fokuserte på en mer spesifikk, men potensielt heterogen gruppe av unge volleyballspillere (@Vissing2008;@Harput2023). Selv om informasjon om gruppene kan være mangelfull, ser de fleste studiene ut til å ha relativt homogene utvalg med hensyn til treningsstatus og idrettsbakgrunn.  

Det er blitt brukt varierende metoder for å rekruttere deltakere i studiene, og graden av detaljer informasjon om rekruttering og begrunnelse for utvalgsstørrelse varierer. Både Vissing et al. (2008) og Fatouros et al. (2000) rekrutterte frivillige (@Fatouros2000;@Vissing2008), mens Harput et al. (2023) brukte en kohort av volleyballspillere (@Harput2023). De to siste studiene gir derimot lite informasjon om rekrutteringsprosessen, men det kan virke som deltagerne er rekruttert fra lokale ungdomslag. 

Kun Vissing et al. (2008) rapporterte en power-beregning for å sikre tilstrekkelig statistisk styrke (0.8), mens de andre ikke oppga dette (@Vissing2008, s.1830). Power referer til sannsynligheten for å oppdage en statistisk signifikant forskjell i utfall mellom gruppene, gitt at det eksisterer en slik forskjell (@browner2022, s.6). En power-beregning beregner hvor mange deltakere som trengs i hver gruppe av studien for å ha en viss sannsynlighet for å finne en signifikant forskjell dersom den finnes (@browner2022, s.6) Når Vissing et al. (2008) oppgir en power på 0.8, betyr det at de med 80% sannsynlighet vil kunne oppdage en forskjell dersom den eksisterer. Mangel på power-beregning i de andre studiene kan svekke deres evne til å trekke pålitelige konklusjoner. 


Neste avsnitt skriver eg om spørsmål 9. og 10.
9. Describe how the study was conducted (what tests was performed when etc.)
10. Describe the variables in the study, what variables relate to the question/hypothesis?

Her er det ganske rett frem. Bruk pensumboken for kva tester som har blitt brukt. Kva variabler har blitt brukt og kvifor er dei relevante?

Rund av med kva for statistiske tester/analyser har dei brukt for å gjøre interferens? Spm 11.
11. What methods did the authors use to make claims (what statistical tests were used)

## Resultat

Svar på spørsmål 12
12. What were the main results of the study, did the authors answer their question/address their hypothesis?

Oppsummer resultatene deires, er det noko forskjell? Har dei svart på det dei ønsket?

## Slutninger

Skriv eit avsnitt der du svarer på både spm 13. og 14
13. What could the authors conclude from the study?
14. What did the authors conclude about the study population?

# Avrunding

Kom med din anbefaling for hvordan fremtidige studier bør designes for best mulig å undersøke effekten av plyometrisk trening på muskelstyrke.

Kort og konsist - kan bruke pensumboken for å begrunne kvifor. 

Se om du kan skal oppsummere alt i en tabell? Ref side 7 [her](https://bartlettje.github.io/pdfs/2021-10-06-learning-to-read-scientific-journal-articles.pdf)
